/* ===================== THE EDITOR'S WRITE-BACK ENDPOINT =====================

   A Vite dev-server plugin. The editor at /admin posts here and this rewrites
   the real source files, so an edit lands in git like any other change and
   ships on the next deploy.

   `apply: 'serve'` is the important line: this exists only while `npm run dev`
   is running. There is no such endpoint in a production build, so the live
   site has nothing to authenticate and nothing to attack.                   */

import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join, resolve } from 'path';

const HERE = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(HERE, '..', 'src');

const read = (rel) => readFileSync(join(SRC, rel), 'utf8');
const write = (rel, text) => writeFileSync(join(SRC, rel), text);

/* Serialise as JS source rather than JSON.stringify's output so the file stays
   pleasant to open and diff by hand — which matters, because these edits are
   reviewed in a pull request like any other. */
const quote = (s) => JSON.stringify(String(s));

const objectSource = (obj, indent = '  ') => {
  const lines = Object.entries(obj).map(([k, v]) => {
    const key = /^[A-Za-z_$][\w$]*$/.test(k) ? k : quote(k);
    if (v && typeof v === 'object' && !Array.isArray(v)) {
      return `${indent}${key}: ${objectSource(v, indent + '  ')},`;
    }
    return `${indent}${key}: ${typeof v === 'number' ? v : quote(v)},`;
  });
  return `{\n${lines.join('\n')}\n${indent.slice(2)}}`;
};

const CONTENT_HEADER = `/* ============================= SITE COPY =============================

   Every piece of text a visitor reads, in one place, so wording can be changed
   without going hunting through every game file.

   THIS FILE IS GENERATED BY THE EDITOR at /admin (dev only). Hand edits are
   fine and survive, but keep it plain data: no imports, no logic, no template
   literals. Anything cleverer than a string will not survive the round trip.

   \`{count}\` and \`{name}\` are filled in at render time.                     */

export const CONTENT = `;

const CONTENT_FOOTER = `;

/* Fills {count}, {name} and friends. Missing keys are left alone rather than
   blanked, so a typo in the editor shows up as visible text instead of a hole
   in the page. */
export const fill = (text, values = {}) =>
  String(text).replace(/\\{(\\w+)\\}/g, (whole, key) =>
    (key in values ? String(values[key]) : whole));

export default CONTENT;
`;

const saveContent = (content) => {
  write('content.js', CONTENT_HEADER + objectSource(content) + CONTENT_FOOTER);
};

/* theme.js holds logic as well as data, so only the three data blocks are
   swapped. Each replacement is checked, and a miss throws rather than writing
   a half-updated file. */
const replaceBlock = (source, declaration, obj) => {
  const re = new RegExp(`(${declaration}\\s*=\\s*)\\{[\\s\\S]*?\\n\\};`, 'm');
  if (!re.test(source)) throw new Error(`could not find "${declaration}" in theme.js`);
  return source.replace(re, (m, head) => `${head}${objectSource(obj)};`);
};

const saveTheme = ({ light, dark, type }) => {
  let s = read('shared/theme.js');
  if (light) s = replaceBlock(s, 'const LIGHT', light);
  if (dark) s = replaceBlock(s, 'const DARK', dark);
  if (type) s = replaceBlock(s, 'export const TYPE', type);
  write('shared/theme.js', s);
};

const body = (req) => new Promise((ok, fail) => {
  let raw = '';
  req.on('data', (c) => { raw += c; if (raw.length > 1e6) req.destroy(); });
  req.on('end', () => { try { ok(JSON.parse(raw)); } catch (e) { fail(e); } });
  req.on('error', fail);
});

export default function adminWriter() {
  return {
    name: 'puzzlr-admin-writer',
    apply: 'serve',
    configureServer(server) {
      server.middlewares.use('/__admin/save', async (req, res, next) => {
        if (req.method !== 'POST') return next();
        try {
          const payload = await body(req);
          if (payload.content) saveContent(payload.content);
          if (payload.light || payload.dark || payload.type) saveTheme(payload);
          res.setHeader('content-type', 'application/json');
          res.end(JSON.stringify({ ok: true, wrote: Object.keys(payload) }));
        } catch (err) {
          res.statusCode = 500;
          res.setHeader('content-type', 'application/json');
          res.end(JSON.stringify({ ok: false, error: String(err && err.message || err) }));
        }
      });
    },
  };
}
