/* ============================= SITE COPY =============================

   Every piece of text a visitor reads, in one place, so wording can be changed
   without going hunting through every game file.

   THIS FILE IS GENERATED BY THE EDITOR at /admin (dev only). Hand edits are
   fine and survive, but keep it plain data: no imports, no logic, no template
   literals. Anything cleverer than a string will not survive the round trip.

   `{name}` is filled in at render time.                                     */

export const CONTENT = {
  hub: {
    eyebrow: "A little arcade of quick games",
    headlineTop: "Play, guess,",
    headlineBottom: "and outsmart a friend.",
    intro: "Hand-built games in one place. No sign-up, no timer pressure. Just open one and go.",
    cardCta: "Play →",
    backToGames: "All games",
    footer: "{name} — a small collection of games. Built for fun.",
  },
  games: {
    wordle: {
      name: "Wordl Unlimited",
      tag: "Word guessing",
      blurb: "Guess the five-letter word in six tries. Play today's daily puzzle — then keep going with unlimited words.",
      players: "1 player",
    },
    wavelength: {
      name: "Wavelength",
      tag: "Read minds",
      blurb: "Read your friends' minds. One player gives a clue, everyone else guesses where it sits on a hidden scale. Two to seven players, online over an invite link.",
      players: "2 players",
    },
    tictactoe: {
      name: "Tic-Tac-Toe",
      tag: "Classic 3-in-a-row",
      blurb: "The classic three-in-a-row, for two players on one device or online with a friend.",
      players: "2 players",
    },
    flags: {
      name: "Flag Quiz",
      tag: "Guess the country",
      blurb: "Name the country from its flag. Race the clock on your own or challenge a friend online. Nearly two hundred flags.",
      players: "1 player",
    },
    connect4: {
      name: "Connect 4",
      tag: "Four in a row",
      blurb: "Drop your discs and get four in a row before your opponent does. Two players on one device, or online over an invite link.",
      players: "2 players",
    },
    hangman: {
      name: "Hangman",
      tag: "Save the cowboy",
      blurb: "Guess the word one letter at a time and save the cowboy. A new daily word  every day, a bot to play against, or pass and play with friends.",
      players: "1-6 players",
    },
    imposter: {
      name: "Imposter",
      tag: "Spot the faker",
      blurb: "Everyone sees the same secret word — except one player. Talk your way through the round and spot the faker. Three to ten players on one device.",
      players: "3-10 players",
    },
    snake: {
      name: "Snake",
      tag: "Eat, grow, don't crash",
      blurb: "Guide the snake around the board, eat apples and grow.",
      players: "1 player",
    },
    minesweeper: {
      name: "Minesweeper",
      tag: "Clear the board, dodge the mines",
      blurb: "Uncover every safe square without hitting a mine.",
      players: "1 player",
    },
    "2048": {
      name: "2048",
      tag: "Slide, merge, reach 2048",
      blurb: "Slide the tiles, merge matching numbers and build your way to 2048. Play the classic four-by-four, or give yourself more room on a bigger board.",
      players: "1 player",
    },
    tetris: {
      name: "Tetris",
      tag: "Stack, clear, survive",
      blurb: "Fit the falling pieces together and clear lines before the stack reaches the top. Hold a piece for later, plan with the preview, and clear four rows at once for the big score.",
      players: "1 player",
    },
  },
  intros: {
    snake: "Eat apples, grow longer, and do not hit the wall or yourself. ",
    minesweeper: "Uncover every square that is not a mine. ",
    minesweeperHint: "Right-click, or press and hold on a phone, to plant a flag. Tapping a number that already has all its flags opens the squares around it.",
    hangman: "Guess the word one letter at a time. Seven wrong guesses and the cowboy is done for.",
    snakeControls: "Arrow keys or WASD, swipe on the board, or use the pad. Space pauses.",
    game2048: "Arrow keys or WASD, or swipe the board. Matching tiles merge into one — but each tile only merges once per move.",
    tetris: "Arrow keys or A and D to move, space to rotate, down to drop faster, up to slam it down, C to hold. On a phone: swipe to move, tap to rotate, hold to drop — or use the buttons.",
  },
  common: {
    daily: "Daily",
    unlimited: "Unlimited",
    playAgain: "Play again",
    newBoard: "New board",
    restart: "Restart",
    share: "Share",
    copied: "Copied!",
    copyFailed: "Copy failed",
  },
};

/* Fills {count}, {name} and friends. Missing keys are left alone rather than
   blanked, so a typo in the editor shows up as visible text instead of a hole
   in the page. */
export const fill = (text, values = {}) =>
  String(text).replace(/\{(\w+)\}/g, (whole, key) =>
    (key in values ? String(values[key]) : whole));

export default CONTENT;
